### ISSUE TITLE
数据库中的数据都是空的，如何造一些测试数据呢

### ISSUE THREAD

**Issue by 289562326** [SnowNation101/Lightning#1]

**Comment by SnowNation101** [comment]
You can try random some data in your database according to the data format in the repo layer. 
Sorry for not being able to provide the real data. 😭

**Comment by xiaonaigao** [comment]
怎样造一些测试数据呢，可以看一下吗，老师

**Comment by SnowNation101** [comment]
The value is 0 after sunset and peaks at noon

**Comment by xiaonaigao** [comment]
> The value is 0 after sunset and peaks at noon

您好，可以求个包含数据的sql文件吗，自己不知道怎样构造，感觉数据集很庞大。

**Comment by SnowNation101** [comment]
Sorry, we can't.
